inputs:
  firebase_options:
    requered: true
  google_services:
    requered: true

runs:
  using: "composite"
  steps:
    - name: create firebase options
      uses: 1arp/create-a-file-action@0.2
      with:
        path: 'lib'
        file: 'firebase_options.dart'
        content: ${{ inputs.firebase_options}}
    - name: create google services
      uses: 1arp/create-a-file-action@0.2
      with:
        path: 'android/app'
        file: 'google-services.json'
        content: ${{ inputs.google_services}}
   s