name: Codecov

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Run tests with coverage
        run: |
          flutter test --coverage
          lcov --list coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
