name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.2'
          channel: "stable"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      #      - name: Install packages
      #        run: cd ert_lint && flutter pub get
      #      - name: Install packages
      #        run: cd ucp_lint && flutter pub get
      - name: Install packages
        run: flutter pub get
      - name: Linter
        continue-on-error: true
        run: flutter analyze --no-fatal-warnings --no-fatal-infos --no-pub

  test:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.2'
          channel: "stable"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - name: Install packages
        run: flutter pub get
      - name: Tester
        run: flutter test

  buildAndRelease:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.2'
          channel: "stable"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - name: Install packages
        run: flutter pub get
      - name: Build APK
        continue-on-error: true
        run: flutter build apk
      - name: Build appbundle
        continue-on-error: true
        run: flutter build appbundle
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.GH_AUTORELEASE_SECRET}}
#          release artifacts only
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  releaseArtifacts:
    runs-on: "ubuntu-latest"
    needs: [ lint, test, buildAndRelease ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-apk
      - uses: actions/download-artifact@v3
        with:
          name: release-bundle
      - name: Display structure of downloaded files
        run: ls -R
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_AUTORELEASE_SECRET }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release Build"
          files: |
            app-release.apk
            app-release.aab