name: Telegram Notification

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs: 
  telegram_fail:
    name: Send Telegram Build Info
    timeout-minutes: 5
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            {{#success build.status}}
            ️Build completed successfully
            {{else}}
            Build failed
            {{/success}}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
